import 'dotenv/config';
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  // Path to the schema definitions; keeping it in a dedicated directory improves project structure
  schema: './schema/index.ts',
  // Output directory for SQL migrations generated by drizzle-kit
  out: './drizzle',
  // Specifies the database engine to ensure correct SQL syntax generation
  dialect: 'postgresql',
  dbCredentials: {
    // Using environment variables for the connection string is a security best practice to avoid leaking credentials
    url: process.env.DATABASE_URL!,
  },
  // 'strict' ensures that the generated migrations are always in sync with the schema, preventing drift
  strict: true,
  // 'verbose' provides detailed logs, which is helpful for debugging migration generation
  verbose: true,
});
